map f7 load_config_file
map ctrl+esc combine : clear_terminal scroll active : send_text normal,application \x0c

# Unmap defaults {{{
# paste_from_selection
map ctrl+shift+s
# }}}

# Sessions {{{
# https://sw.kovidgoyal.net/kitty/sessions/
# a as in assembly
map ctrl+alt+a>shift+o goto_session --sort-by alphabetical ~/.local/share/kitty/sessions
map ctrl+alt+a>shift+s save_as_session --use-foreground-process --base-dir ~/.local/share/kitty/sessions
map ctrl+alt+a>shift+c close_session .
map ctrl+alt+a>c goto_session ~/.local/share/kitty/sessions/confNest.kitty-session
map ctrl+alt+a>s goto_session ~/.local/share/kitty/sessions/shsu.kitty-session
# }}}

## Layouts {{{
# https://sw.kovidgoyal.net/kitty/layouts/
enabled_layouts splits:equalize_on_close=true:split_axis=auto,stack,tall,fat
map ctrl+alt+s toggle_layout stack
map ctrl+alt+shift+s goto_layout splits
map ctrl+alt+p last_used_layout
map ctrl+alt+n next_layout

# Rotate the current split, changing its split axis from vertical to
# horizontal or vice versa
map ctrl+alt+r layout_action rotate
# }}}

# Windows {{{
# New in the current working directory
map kitty_mod+enter new_window_with_cwd

map ctrl+alt+h launch --hold-after-ssh --cwd=current --location=hsplit
map ctrl+alt+v launch --hold-after-ssh --cwd=current --location=vsplit
map ctrl+alt+j launch --hold-after-ssh --cwd=current --location=split

# https://sw.kovidgoyal.net/kitty/layouts/
map kitty_mod+h neighboring_window left
map kitty_mod+l neighboring_window right
map kitty_mod+k neighboring_window up
map kitty_mod+j neighboring_window down

# Resizing windows
map ctrl+left resize_window narrower 2
map ctrl+right resize_window wider 3
map ctrl+up resize_window taller 2
map ctrl+down resize_window shorter 2
# }}}

# Tabs {{{
# New in the current working directory
map kitty_mod+t new_tab_with_cwd

map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9
# }}}

# Kittens {{{
# Open URL
map kitty_mod+e open_url_with_hints

# Open selected path
map kitty_mod+p>shift+f kitten hints --type path

# Open the selected hyperlink
map kitty_mod+p>o kitten hints --type hyperlink

# Insert selected path
map kitty_mod+p>f kitten hints --type path --program -
# }}}

# Having fun {{{
map kitty_mod+p>s launch --hold --type=tab --stdin-source=@screen_scrollback --stdin-add-formatting --env LESSUTFCHARDEF="e000-e09f:w,e0a0-e0bf:p,e0c0-f8ff:w,f0001-fffff:w" /usr/bin/bat --plain
map kitty_mod+/ open_url https://sw.kovidgoyal.net/kitty
# Increase background opacity
map --allow-fallback=ascii ctrl+shift+a>m set_background_opacity +0.02
# Decrease background opacity
map --allow-fallback=ascii ctrl+shift+a>l set_background_opacity -0.02
# }}}

# Mouse mappings {{{
mouse_map left press ungrabbed mouse_selection normal
mouse_map ctrl+left press ungrabbed mouse_selection drag_or_normal_select
# }}}

# vim:fileencoding=utf-8:foldmethod=marker
