# https://sw.kovidgoyal.net/kitty/open_actions/

# Open any file with fragment in the editor. Fragments are generated
# by the hyperlinked_grep kitten and nothing.
protocol file
fragment_matches [0-9]+
action launch --type=tab $EDITOR +$FRAGMENT $FILE_PATH

# Open text files without fragments in the editor
protocol file
mime text/*
action launch --type=tab $EDITOR $FILE_PATH

# Open image files in an overlay window with icat
protocol file
mime image/*
action launch --type=tab kitty +kitten icat --hold $FILE_PATH
