#!/bin/bash

symlink() {
  local source=$1
  local destination=$2

  echo -n "Symlink ${source} ... "
  if [[ -e $destination ]]; then
    echo "Already exists"
  else
    ln -s "$(pwd)/${source}" $destination
    echo "Done"
  fi
}

install_jet_brains_mono() {
  local jbm_fonts_installed=~/.local/share/fonts/JetBrains_Mono_is_installed.txt

  if [[ -e $jbm_fonts_installed ]]; then
    echo "JetBrains Mono Nerd Fonts are already installed"
  else
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh)"
    touch $jbm_fonts_installed
  fi
}

symlink_lvim_config() {
  local link=~/.config/lvim/config.lua

  if [[ -e $link ]]; then
    rm -rf $link
    symlink lvim_config.lua $link
  else
    echo "Lvim is not installed"
  fi
}

symlink gitconfig ~/.gitconfig
symlink gitignore_global ~/.gitignore_global

symlink bash_aliases ~/.bash_aliases

symlink terminator ~/.config/terminator

symlink nvim ~/.config/nvim
symlink_lvim_config

install_jet_brains_mono
