#!/bin/bash

symlink_file() {
  local source=$1
  local destination=$2

  echo -n "Symlink ${source} ... "
  if [[ -e $destination ]]; then
    echo "Already exists"
  else
    ln -s "$(pwd)/${source}" $destination
    echo "Done"
  fi
}

symlink_file gitconfig ~/.gitconfig
symlink_file git-prompt.sh ~/.git-prompt.sh
symlink_file gitignore_global ~/.gitignore_global

symlink_file bash_aliases ~/.bash_aliases

symlink_file terminator ~/.config/terminator
