#!/bin/bash

symlink() {
  local source=$1
  local destination=$2

  echo -n "Symlink ${source}... "
  if [[ -e $destination ]]; then
    echo "Already exists"
  else
    ln -s "$(pwd)/${source}" $destination
    echo "Done"
  fi
}

install_jetbrains_mono_nerd_font() {
  local font_url="https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/patched-fonts/JetBrainsMono/Ligatures/Regular/complete/JetBrains%20Mono%20Regular%20Nerd%20Font%20Complete%20Mono.ttf"

  local font_dir=~/.local/share/fonts
  local font_file="$font_dir/JetBrains_Mono_Regular_Nerd_Font_Complete_Mono.ttf"

  echo -n "Installing JetBrains Mono Regular Nerd Font... "

  if [ -f "$font_file" ] && [ -z $RELOAD_FONT ]; then
    echo "Already installed"
  else
    mkdir -p $font_dir
    curl -s -o "$font_file" "$font_url"
    fc-cache -f || die "Unable to build fonts cache"
    echo "Done"
  fi
}

symlink_lvim_config() {
  local link=~/.config/lvim/config.lua

  if [[ -e $link ]]; then
    rm -rf $link
    symlink lvim/config.lua $link
    symlink lvim/lua ~/.config/lvim/lua
  else
    echo "Lvim is not installed"
  fi
}

symlink gitconfig ~/.gitconfig
symlink gitignore_global ~/.gitignore_global

symlink bash_aliases ~/.bash_aliases

symlink terminator ~/.config/terminator

symlink nvim ~/.config/nvim
symlink_lvim_config

install_jetbrains_mono_nerd_font
