HISTSIZE=32768
HISTFILESIZE=$HISTSIZE

PATH="./bin:$PATH"
[ -d ~/.cargo/bin ] && PATH="$PATH:$HOME/.cargo/bin"

source $OMAKUB_PATH/configs/shell/aliases

command -v zoxide > /dev/null && eval "$(zoxide init bash)"
command -v fzf > /dev/null && source /usr/share/doc/fzf/examples/key-bindings.bash

if [ -s "$HOME/.nvm/nvm.sh" ]; then
  export NVM_DIR="$HOME/.nvm"
  source "$NVM_DIR/nvm.sh"
  source "$NVM_DIR/bash_completion"
fi

[ -s ~/.rvm/scripts/rvm ] && source ~/.rvm/scripts/rvm

export VISUAL=$(which lvim)
export EDITOR="$VISUAL"
export SUDO_EDITOR="$VISUAL"

saysomething
