HISTSIZE=32768
HISTFILESIZE=$HISTSIZE

declare -x VISUAL
VISUAL=$(which lvim)
export EDITOR="$VISUAL"
export SUDO_EDITOR=vim

export MISE_EXEC_AUTO_INSTALL=false
export MISE_NOT_FOUND_AUTO_INSTALL=false
test -d ~/.local/share/mise/shims && PATH="$_:$PATH"

PATH="./bin:$CONFIGS_DIR/bin:$PATH"
test -d ~/.cargo/bin && PATH="$PATH:$_"

source "$CONFIGS_DIR/bash/functions.sh"
source_all "$CONFIGS_DIR"/bash/rc.d/*.sh

# Load RVM
test -s ~/.rvm/scripts/rvm && source "$_"
