HISTSIZE=32768
HISTFILESIZE=$HISTSIZE

declare -x VISUAL
VISUAL=$(which lvim)
export EDITOR="$VISUAL"
export SUDO_EDITOR=vim

PATH="./bin:$PATH"
[ -d ~/.cargo/bin ] && PATH="$PATH:$HOME/.cargo/bin"

command -v zoxide > /dev/null && eval "$(zoxide init bash)"
command -v fzf > /dev/null && source /usr/share/doc/fzf/examples/key-bindings.bash

if [ -s "$HOME/.nvm/nvm.sh" ]; then
  export NVM_DIR="$HOME/.nvm"
  # shellcheck source=~/.nvm/nvm.sh
  source "$NVM_DIR/nvm.sh"
  # shellcheck source=~/.nvm/bash_completion
  source "$NVM_DIR/bash_completion"
fi

[ -s ~/.rvm/scripts/rvm ] && source ~/.rvm/scripts/rvm

source "$CONFIGS_DIR/bash/functions.sh"
source "$CONFIGS_DIR/bash/prompt.sh"

saysomething
